# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set([('name', 'school')]),
        ),
    ]
