# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160518_0056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('name', 'classroom')]),
        ),
    ]
