# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160518_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([]),
        ),
    ]
